### ISSUE TITLE
Entering move mode with one command

### ISSUE THREAD

**Issue by dataO1** [simeji/winresizer#20]
Hi, 

i cant enter move mode and move a window with one macro like this:
`noremap <silent> <A-h> <A-r>mh<CR>`

I aim for an i3-like behaviour, but the above just does nothing.
Is there a way to make this mapping available in the config?

**Comment by sum01** [comment]
You could keybind to the `WinResizerStartMove` command.

**Comment by dataO1** [comment]
works perfectly, thank you!
