### ISSUE TITLE
Keycodes for size not working with Cursors

### ISSUE THREAD

**Issue by joekinley** [simeji/winresizer#22]
I tried all of those
```
let g:winresizer_keycode_up = '<C-UP>'
let g:winresizer_keycode_up = '<C-up>'
let g:winresizer_keycode_up = '<Up>'
let g:winresizer_keycode_up = '<UP>'
let g:winresizer_keycode_up = '<up>'
```

And similar, but nothing worked. 

Expecting: I expected to be able to use regular cursors for window size movement

**Comment by simeji** [comment]
@joekinley 
Great question :)

Cloud you try the following code.
```
let g:winresizer_keycode_up = "\<UP>"
let g:winresizer_keycode_down = "\<DOWN>"
```
we have to use `"` and `\`.

**Comment by simeji** [comment]
I'll close this issue.
If you have any additional questions, reopen this, please.
