### ISSUE TITLE
Mismatch Message

### ISSUE THREAD

**Issue by hamuhamu** [simeji/winresizer#7]
The message does not change even if I change the settings.

g:winresizer_keycode_finish = 32 (Space)

https://github.com/simeji/winresizer/blob/186e02e2af4a1ec7eaf40ba39db4bebc78f25dcf/plugin/winresizer.vim#L126

It has been hard coding.

```
 echo '[window resize mode]... "Enter": OK , "q": Cancel'
```

◯ [window resize mode]... "Space": OK , "q": Cancel
☓ [window resize mode]... "Enter": OK , "q": Cancel

**Comment by simeji** [comment]
I've never noticed that problem.

I fixed it !
https://github.com/simeji/winresizer/commit/a60597ad121c73459b34aafbc64c2ef74a37738e

Please try to update winresizer.

**Comment by hamuhamu** [comment]
Thank you!!
